name = "RealTimeAudioDiffEq"
uuid = "7a3f4937-0cad-4220-a144-0330815b2118"
authors = ["Antonio Ortega Brook <antonioortegabrook@me.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
