name = "RealTimeAudioDiffEq"
uuid = "7a3f4937-0cad-4220-a144-0330815b2118"
authors = ["Antonio Ortega Brook <antonioortegabrook@me.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
PortAudio = "80ea8bcb-4634-5cb3-8ee8-a132660d1d2d"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
